[package]
name = "awesome-operates"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
build-data = "0.1"
chrono = "0.4"
lazy_static = "*"
regex = "1"
rust_decimal = { version = "1.32", features = ["serde-float"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
