[package]
name = "awesome-operates"
version = "0.1.1"
edition = "2021"
categories = ["asynchronous"]
description = "A reposity includs many common use code utils"
keywords = ["axum", "tokio", "systemd"]
authors = ["Gongzhengyang <gongzhengyangfindyourdream@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/gongzhengyang/awesome-operates"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
build-data = "0.1"
chrono = "0.4"
regex = "1"
rust_decimal = { version = "1.32", features = ["serde-float"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
serde_json = "1"
snafu = "0.7"
axum = { git = "https://github.com/tokio-rs/axum.git" }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.4.0", features = ["trace"] }
hyper = { version = "0.14", features = ["full"] }
mime = "0.3"
